name: CI
on:
  push:
    branches: [ tom ]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: "Hello output1"
   
     
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.job1.outputs.output1}}  
        
   
        
        
        
      
