name: GitHub Actions Demo
on: 
 push:
  branches: ["tom"]
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
env:
  DAY: ${{github.event.push.branches.tom}}
  secret: ${{secrets.secret1}}


jobs:
   
  greeting_job:
    runs-on : ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: script
        run : echo "here is your day $DAY"
               
        
        
        
      
