name: GitHub Actions Demo
on: 
 push:
  branches: ["tom"]
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
env:
  DAY: monday
  secret: ${{secrets.secret1}}


jobs:
   
  greeting_job:
    name: job1
    runs-on : ubuntu-latest
    env:
     DAY: jobs.greeting_job.name
    steps:
      - uses: actions/checkout@v3
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
      - name: script
        run : echo "$DAY"
               
        
        
        
      
