name: GitHub Actions Demo
on: 
 push:
  branches: ["tom"]


jobs:
  job1:
   name: job1111
   strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]
   runs-on: ${{matrix.os}}
   steps:
     - run : echo " LINUX"
     - run : write-host " Windows"
   
        
        
        
      
