name: GitHub Actions Demo
on: 
 push:
  branches: ["tom"]
env:
  DAY_OF_WEEK: Monday
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: env.DAY_OF_WEEK=="Moday"
      - run: echo " Tes it is  $DAY_OF_WEEK"
      
