name: GitHub Actions Demo
on: 
 push:
  branches: ["tom"]
permissions: 
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
env:
  DAY_OF_WEEK: lol222
  secret: ${{secrets.secret1}}


jobs:
   
  greeting_job:
    runs-on : ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: script
        run : -e {./script1.sh}
        
        
        
      
